[tool.poetry]
name = "typer-shell"
version = "0.1.8"
description = "A shell for typer apps with autocompletion and history"
authors = ["fergus <fergusfettes@gmail.com>"]
readme = "README.md"
packages = [{include = "typer_shell"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
typer = "^0.9.0"
click = "^8.1.3"
rich = "^13.3.5"
click-shell = "^2.1"
iterfzf = "^0.5.0.20.0"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
